### ISSUE TITLE
まだ就職中なんですか?

### ISSUE THREAD

**Issue by yuzuka4573** [defaultcf/i544c#2]
もうご卒業したと聞いていますが…
ひょっとして僕の仲間ですか?

**Comment by defaultcf** [comment]
@yuzuka4573 
> まだ就職中なんですか?

就職したよ。君こそ求職の旨をREADMEに掲げよう。
https://docs.github.com/ja/github/setting-up-and-managing-your-github-profile/managing-your-profile-readme
（リンク間違ってた）

**Comment by yuzuka4573** [comment]
ネタがないのでcloseします

**Comment by defaultcf** [comment]
:cry:
